### ISSUE TITLE
ROCKY/RHEL 9.5 - build issue

### ISSUE THREAD

**Issue by AlexeySaff** [cisco/exanic-software#97]
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 2, 0)
static int exanic_phc_adjfine(struct ptp_clock_info *ptp, long scaled_ppm)
#else
static int exanic_phc_adjfreq(struct ptp_clock_info *ptp, s32 delta)

but in 9.5 adjfreq has been removed and the kernel is still 5.14

also

**Comment by AlexeySaff** [comment]
not a big user of git, but here is patch file to apply on top of el94 patch


if someone wants to test it or change, feel free. right now official position of CISCO TAC is no support for 9.4/9.5 and not in pipeline


`diff --git a/exanic.spec b/exanic.spec
index 2c500c9..8fd95ab 100644
--- a/exanic.spec
+++ b/exanic.spec
@@ -1,5 +1,5 @@
 Name:           exanic
-Version:        2.7.4-git-el9_4
+Version:        2.7.4-git-el9_5
 Release:        2%{?dist}
 
 Summary:        ExaNIC drivers and software
diff --git a/modules/exanic/exanic-dev.c b/modules/exanic/exanic-dev.c
index 62821d7..d001379 100644
--- a/modules/exanic/exanic-dev.c
+++ b/modules/exanic/exanic-dev.c
@@ -317,7 +317,8 @@ static int exanic_map_tx_feedback(struct exanic *exanic,
     int err;
     struct device *dev = &exanic->pci_dev->dev;
     size_t map_size = vma->vm_end - vma->vm_start;
-#if LINUX_VERSION_CODE < KERNEL_VERSION(6, 1, 2)
+#if (defined(RHEL_MAJOR) && (RHEL_MAJOR == 9 && RHEL_MINOR < 5)) || \
+                                           LINUX_VERSION_CODE < KERNEL_VERSION(6, 1, 2)
     size_t off;
 #endif
     phys_addr_t phys_addr;
@@ -333,7 +334,7 @@ static int exanic_map_tx_feedback(struct exanic *exanic,
     }
 
     /* Do the mapping */
-#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 2)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 2) || (defined(RHEL_MAJOR) && RHEL_MAJOR == 9 && RHEL_MINOR == 5)
     vma->vm_pgoff = 0;
     err = dma_mmap_coherent(dev, vma, exanic->tx_feedback_virt,
             exanic->tx_feedback_dma, map_size);
@@ -378,7 +379,7 @@ static int exanic_map_rx_region(struct exanic *exanic, struct vm_area_struct *vm
     int err;
     struct device *dev = &exanic->pci_dev->dev;
     void *rx_region_virt;
-#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 2)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 2) || (defined(RHEL_MAJOR) && RHEL_MAJOR == 9 && RHEL_MINOR == 5)
     dma_addr_t rx_region_dma;
 #else
     size_t off;
@@ -390,7 +391,7 @@ static int exanic_map_rx_region(struct exanic *exanic, struct vm_area_struct *vm
     {
         rx_region_virt =
           exanic->port[port_num].filter_buffers[buffer_num - 1].region_virt;
-#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 2)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 2) || (defined(RHEL_MAJOR) && RHEL_MAJOR == 9 && RHEL_MINOR == 5)
         rx_region_dma =
           exanic->port[port_num].filter_buffers[buffer_num - 1].region_dma;
 #endif
@@ -398,7 +399,7 @@ static int exanic_map_rx_region(struct exanic *exanic, struct vm_area_struct *vm
     else
     {
         rx_region_virt = exanic->port[port_num].rx_region_virt;
-#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 2)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 2) || (defined(RHEL_MAJOR) && RHEL_MAJOR == 9 && RHEL_MINOR == 5)
         rx_region_dma = exanic->port[port_num].rx_region_dma;
 #endif
     }
@@ -471,7 +472,7 @@ static int exanic_map_rx_region(struct exanic *exanic, struct vm_area_struct *vm
     }
 
     /* Do the mapping */
-#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 2)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 2) || (defined(RHEL_MAJOR) && RHEL_MAJOR == 9 && RHEL_MINOR == 5)
     vma->vm_pgoff = 0;
     err = dma_mmap_coherent(dev, vma, rx_region_virt,
             rx_region_dma, map_size);
diff --git a/modules/exanic/exanic-ptp.c b/modules/exanic/exanic-ptp.c
index 300ebcc..cf92969 100644
--- a/modules/exanic/exanic-ptp.c
+++ b/modules/exanic/exanic-ptp.c
@@ -375,7 +375,8 @@ static bool exanic_ptp_adj_allowed(struct exanic *exanic)
     return true;
 }
 
-#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 2, 0)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 2, 0) || (defined(RHEL_MAJOR) && \
+		(RHEL_MAJOR == 9) && (RHEL_MINOR == 5))
 static int exanic_phc_adjfine(struct ptp_clock_info *ptp, long scaled_ppm)
 {
     struct exanic *exanic = container_of(ptp, struct exanic, ptp_clock_info);
@@ -649,7 +650,8 @@ static int exanic_phc_enable(struct ptp_clock_info *ptp,
 static const struct ptp_clock_info exanic_ptp_clock_info = {
     .owner      = THIS_MODULE,
     .pps        = 1,
-#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 2, 0)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 2, 0) || (defined(RHEL_MAJOR) && \
+                (RHEL_MAJOR == 9) && (RHEL_MINOR == 5))
     .adjfine    = exanic_phc_adjfine,
 #else
     .adjfreq    = exanic_phc_adjfreq,
diff --git a/modules/exasock/exasock-tcp.c b/modules/exasock/exasock-tcp.c
index eeb4fa3..98f0dc4 100644
--- a/modules/exasock/exasock-tcp.c
+++ b/modules/exasock/exasock-tcp.c
@@ -1426,9 +1426,8 @@ static void exasock_tcp_dead(struct kref *ref)
 /* need biglock for this one function to avoid race condition */
 #if LINUX_VERSION_CODE < KERNEL_VERSION(2, 6, 36)
 static DECLARE_MUTEX(update_biglock);
-#elif LINUX_VERSION_CODE < KERNEL_VERSION(6, 4, 0)
-static DEFINE_SEMAPHORE(update_biglock);
-#else
+#elif defined(RHEL_MAJOR) && ((RHEL_MAJOR == 9 && RHEL_MINOR < 5)) || \
+					   LINUX_VERSION_CODE < KERNEL_VERSION(6, 4, 0)
 static DEFINE_SEMAPHORE(update_biglock, 1);
 #endif
 int exasock_tcp_update(struct exasock_tcp *tcp,
`

**Comment by cyriljose22** [comment]
We are facing following error during `make`.

```
[root@localhost exanic-software-master]# make
make -C modules/exanic
make[1]: Entering directory '/root/exanic-software-master/modules/exanic'
make -C /lib/modules/`uname -r`/build M=$PWD modules
make[2]: Entering directory '/usr/src/kernels/5.14.0-503.14.1.el9_5.x86_64'
  CC [M]  /root/exanic-software-master/modules/exanic/exanic-main.o
/root/exanic-software-master/modules/exanic/exanic-main.c: In function ‘exanic_probe’:
/root/exanic-software-master/modules/exanic/exanic-main.c:1062:5: error: implicit declaration of function ‘pci_enable_pcie_error_reporting’ [-Werror=implicit-function-declaration]
 1062 |     pci_enable_pcie_error_reporting(pdev);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/exanic-software-master/modules/exanic/exanic-main.c:1887:5: error: implicit declaration of function ‘pci_disable_pcie_error_reporting’ [-Werror=implicit-function-declaration]
 1887 |     pci_disable_pcie_error_reporting(pdev);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:249: /root/exanic-software-master/modules/exanic/exanic-main.o] Error 1
make[2]: *** [Makefile:1944: /root/exanic-software-master/modules/exanic] Error 2
make[2]: Leaving directory '/usr/src/kernels/5.14.0-503.14.1.el9_5.x86_64'
make[1]: *** [Makefile:20: default] Error 2
make[1]: Leaving directory '/root/exanic-software-master/modules/exanic'
make: *** [Makefile:9: modules] Error 2

```

**Comment by AlexeySaff** [comment]
that one has been fixed with patch for el94, please check 
https://github.com/cisco/exanic-software/files/15427480/exanic-software_el9_4.patch.gz

but 9.5 gives another set of errors

and shame on CISCO, zero support from their side.

**Comment by AdiPircalabu** [comment]
The source that builds on 9.4 fails on 9.5, see the attachment.
[make.log.gz](https://github.com/user-attachments/files/18031039/make.log.gz)

**Comment by flare04** [comment]
This is the issue https://lore.kernel.org/netdev/20221109230945.545440-7-jacob.e.keller@intel.com/T/
