### ISSUE TITLE
Build error on Ubuntu 24.04

### ISSUE THREAD

**Issue by chill1n** [cisco/exanic-software#92]
Is it possible to get the software to build on Ubuntu 24.04?
Right now it errors out with:
```
make
make -C modules/exanic
make[1]: Entering directory '/home/developer/workspace/exanic-software/modules/exanic'
make -C /lib/modules/`uname -r`/build M=$PWD modules
make[2]: Entering directory '/usr/src/linux-headers-6.8.0-35-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.2.0-23ubuntu4) 13.2.0
  You are using:           gcc-13 (Ubuntu 13.2.0-23ubuntu4) 13.2.0
  CC [M]  /home/developer/workspace/exanic-software/modules/exanic/exanic-main.o
/home/developer/workspace/exanic-software/modules/exanic/exanic-main.c:233:8: warning: no previous prototype for ‘exanic_alloc_dma’ [-Wmissing-prototypes]
  233 | void * exanic_alloc_dma(struct exanic *exanic, int *numa_node,
      |        ^~~~~~~~~~~~~~~~
/home/developer/workspace/exanic-software/modules/exanic/exanic-main.c:946:5: warning: no previous prototype for ‘exanic_get_num_ports’ [-Wmissing-prototypes]
  946 | int exanic_get_num_ports(struct exanic *exanic)
      |     ^~~~~~~~~~~~~~~~~~~~
/home/developer/workspace/exanic-software/modules/exanic/exanic-main.c: In function ‘exanic_probe’:
/home/developer/workspace/exanic-software/modules/exanic/exanic-main.c:1062:5: error: implicit declaration of function ‘pci_enable_pcie_error_reporting’ [-Werror=implicit-function-declaration]
 1062 |     pci_enable_pcie_error_reporting(pdev);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/developer/workspace/exanic-software/modules/exanic/exanic-main.c:1887:5: error: implicit declaration of function ‘pci_disable_pcie_error_reporting’ [-Werror=implicit-function-declaration]
 1887 |     pci_disable_pcie_error_reporting(pdev);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:243: /home/developer/workspace/exanic-software/modules/exanic/exanic-main.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.8.0-35-generic/Makefile:1926: /home/developer/workspace/exanic-software/modules/exanic] Error 2
make[2]: *** [Makefile:240: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-6.8.0-35-generic'
make[1]: *** [Makefile:20: default] Error 2
make[1]: Leaving directory '/home/developer/workspace/exanic-software/modules/exanic'
make: *** [Makefile:9: modules] Error 2
```

**Comment by Alexxstud** [comment]
See the discussion at https://github.com/cisco/exanic-software/issues/90, some fixes there may help.

**Comment by ApexClock** [comment]
Still having problem with building error on Ubuntu 24.04. Is there a solution? or the most recent driver?

**Comment by Alexxstud** [comment]
@ApexClock, the last driver update seems to be of Dec 21, 2023, 2.7.4. Maybe there is another repository, which Cisco updates regularly, and this one is considered as deprecated.
